# Generated by Django 4.2.16 on 2024-10-23 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.IntegerField(default=10)),
                ('duracion_minutos', models.IntegerField(default=5)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejercicios.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='rutinas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ejercicios', models.ManyToManyField(through='rutinas.EjercicioPersonalizado', to='ejercicios.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='rutinas.rutina')),
            ],
        ),
        migrations.AddField(
            model_name='ejerciciopersonalizado',
            name='entrenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.entrenamiento'),
        ),
    ]
