# Generated by Django 4.2.16 on 2024-10-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_categoria_remove_ejercicio_categoria_and_more'),
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejerciciopersonalizado',
            name='entrenamiento',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='ejercicios',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='rutina',
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='ejercicio_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejerciciopersonalizado'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='entrenamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.entrenamiento'),
        ),
        migrations.AlterField(
            model_name='ejerciciopersonalizado',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ejercicios.ejercicio'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rutinas/'),
        ),
    ]
