# Generated by Django 4.2.16 on 2024-10-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_remove_rutina_entrenamiento_entrenamiento_rutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ejercicio_personalizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejerciciopersonalizado')),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesion', to='rutinas.rutina')),
            ],
        ),
        migrations.DeleteModel(
            name='Entrenamiento',
        ),
    ]
