# Generated by Django 4.2.16 on 2024-10-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_sesion_delete_entrenamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='ejercicio_personalizado',
        ),
        migrations.AddField(
            model_name='ejerciciopersonalizado',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.sesion'),
        ),
    ]
