# Generated by Django 4.2.16 on 2024-10-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0006_remove_ejerciciopersonalizado_duracion_minutos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
