# Generated by Django 4.2.16 on 2024-10-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0007_alter_rutina_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriepersonalizada',
            name='duracion_minutos',
        ),
        migrations.AddField(
            model_name='seriepersonalizada',
            name='descanso',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='seriepersonalizada',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seriepersonalizada',
            name='rer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seriepersonalizada',
            name='velocidad_repeticion',
            field=models.FloatField(default=0),
        ),
    ]
