# Generated by Django 4.2.16 on 2024-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0008_remove_seriepersonalizada_duracion_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciopersonalizado',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
