# Generated by Django 4.2.16 on 2024-10-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0009_ejerciciopersonalizado_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriepersonalizada',
            name='peso',
        ),
    ]
