# Generated by Django 4.2.16 on 2024-10-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0010_remove_seriepersonalizada_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriepersonalizada',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
