# Generated by Django 4.2.16 on 2024-10-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0011_seriepersonalizada_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriepersonalizada',
            name='ejercicio_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='rutinas.ejerciciopersonalizado'),
        ),
    ]
