# Generated by Django 4.2.16 on 2024-10-31 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0012_alter_seriepersonalizada_ejercicio_personalizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejerciciopersonalizado',
            old_name='peso',
            new_name='peso_orden',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
