# Generated by Django 4.2.16 on 2024-10-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0013_rename_peso_ejerciciopersonalizado_peso_orden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejerciciopersonalizado',
            options={'ordering': ['peso_orden']},
        ),
    ]
