# Generated by Django 4.2.16 on 2024-11-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0014_alter_ejerciciopersonalizado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriepersonalizada',
            options={'ordering': ['id']},
        ),
    ]
