version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    volumes:
      - ./postgres_pro:/var/lib/postgresql/data  # Cambiado para guardar los datos en ficheros locales
    ports:
      - "5432:5432"

  web:
    build: .
    command: tail -f /dev/null
    # command: bash -c "python /app/manage.py runserver 0.0.0.0:8000 & tail -f /dev/null"
    volumes:
      - ./src:/app
      # Solo para importar
      - ./exercises_photos:/free-exercise-db
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_NAME=django
      - DJANGO_DB_USER=django
      - DJANGO_DB_PASSWORD=django
      - DJANGO_DB_HOST=db

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/nginx_dev.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs  # Directorio donde guardarás los certificados SSL
    depends_on:
      - web