# Generated by Django 4.2.16 on 2024-10-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serierealizada',
            name='duracion_minutos',
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='descanso',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='rer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='velocidad',
            field=models.FloatField(default=0),
        ),
    ]
