# Generated by Django 4.2.16 on 2024-10-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0002_remove_serierealizada_duracion_minutos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serierealizada',
            old_name='velocidad',
            new_name='velocidad_repeticion',
        ),
    ]
