# Generated by Django 4.2.16 on 2024-10-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0003_rename_velocidad_serierealizada_velocidad_repeticion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='serierealizada',
            name='inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
