# Generated by Django 4.2.16 on 2024-10-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0004_alter_entrenamiento_fin_alter_entrenamiento_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serierealizada',
            name='extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
