# Generated by Django 4.2.16 on 2024-10-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0005_serierealizada_extra_serierealizada_realizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serierealizada',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
