# Generated by Django 4.2.16 on 2024-10-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0007_remove_serierealizada_ejercicio_personalizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serierealizada',
            name='ejercicio_realizado',
        ),
        migrations.AddField(
            model_name='serierealizada',
            name='ejercicio_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.ejerciciorealizado'),
        ),
    ]
