# Generated by Django 4.2.16 on 2024-10-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0008_remove_serierealizada_ejercicio_realizado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serierealizada',
            old_name='ejercicio_personalizado',
            new_name='ejercicio_realizado',
        ),
    ]
