# Generated by Django 4.2.16 on 2024-10-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0009_rename_ejercicio_personalizado_serierealizada_ejercicio_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serierealizada',
            name='ejercicio_realizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='entrenamiento.ejerciciorealizado'),
        ),
    ]
