# Generated by Django 4.2.16 on 2024-10-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0011_remove_serierealizada_peso_serierealizada_peso_orden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serierealizada',
            old_name='peso_orden',
            new_name='peso',
        ),
    ]
