# Generated by Django 4.2.16 on 2024-10-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='equipamiento/')),
            ],
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='musculos/')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.TextField()),
                ('imagen_uno', models.ImageField(blank=True, null=True, upload_to='ejercicios/')),
                ('imagen_dos', models.ImageField(blank=True, null=True, upload_to='ejercicios/')),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('equipamiento', models.ManyToManyField(blank=True, null=True, related_name='ejercicios', to='ejercicios.equipamiento')),
                ('musculo_primario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_principales', to='ejercicios.musculo')),
                ('musculo_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_secundarios', to='ejercicios.musculo')),
            ],
        ),
    ]
