# Generated by Django 4.2.16 on 2024-10-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='categoria/')),
            ],
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, related_name='categoria', to='ejercicios.categoria'),
        ),
    ]
