# Generated by Django 4.2.16 on 2024-10-23 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_categoria_remove_ejercicio_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='equipamiento',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='ejercicios.categoria'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='equipamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='ejercicios.equipamiento'),
        ),
    ]
