# Generated by Django 4.2.16 on 2024-11-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_remove_ejercicio_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='realizar_por_extremidad',
            field=models.BooleanField(default=False),
        ),
    ]
