# Generated by Django 4.2.16 on 2024-12-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0004_ejercicio_realizar_por_extremidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='musculos/'),
        ),
    ]
